# Generated by Django 4.2.7 on 2023-11-28 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacityId', models.CharField(max_length=200)),
                ('capacityName', models.CharField(max_length=200)),
                ('insertedDate', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 4, 47, 26, 233421, tzinfo=datetime.timezone.utc), verbose_name='Created at:')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBI_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('tenant_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('insertedDate', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 4, 47, 26, 169519, tzinfo=datetime.timezone.utc), verbose_name='Created at:')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspaceId', models.CharField(max_length=200)),
                ('workspaceName', models.CharField(max_length=200)),
                ('insertedDate', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 4, 47, 26, 233421, tzinfo=datetime.timezone.utc), verbose_name='Created at:')),
                ('capacityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbiwebapp.capacity')),
            ],
        ),
        migrations.AddField(
            model_name='capacity',
            name='powerbi_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbiwebapp.powerbi_setting'),
        ),
    ]
