# Generated by Django 4.2.7 on 2023-11-28 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbiwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 15, 56, 933585, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='powerbi_setting',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 15, 56, 868637, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 15, 56, 934585, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetId', models.CharField(max_length=200)),
                ('datasetName', models.CharField(max_length=200)),
                ('insertedDate', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 15, 56, 934585, tzinfo=datetime.timezone.utc), verbose_name='Created at:')),
                ('workspaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbiwebapp.workspace')),
            ],
        ),
    ]
