# Generated by Django 5.0.1 on 2024-01-04 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbiwebapp', '0002_alter_capacity_inserteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 2, 23, 218696, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='powerbi_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pbiwebapp.powerbi_setting'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 2, 23, 219696, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='workspaceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pbiwebapp.workspace'),
        ),
        migrations.AlterField(
            model_name='powerbi_setting',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 2, 23, 182699, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='capacityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pbiwebapp.capacity'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 2, 23, 219696, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
    ]
