# Generated by Django 5.0.1 on 2024-01-04 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbiwebapp', '0004_alter_capacity_inserteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 6, 53, 330086, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='powerbi_setting',
            field=models.ForeignKey(on_delete=models.SET(0), to='pbiwebapp.powerbi_setting'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 6, 53, 331087, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='workspaceId',
            field=models.ForeignKey(on_delete=models.SET(0), to='pbiwebapp.workspace'),
        ),
        migrations.AlterField(
            model_name='powerbi_setting',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 6, 53, 286150, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='capacityId',
            field=models.ForeignKey(on_delete=models.SET(0), to='pbiwebapp.capacity'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='insertedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 6, 53, 331087, tzinfo=datetime.timezone.utc), verbose_name='Created at:'),
        ),
    ]
